### ISSUE TITLE
change Xemex.co to reflect /sports or /trading  

### ISSUE THREAD

**Issue by laisee** [BBNinja/bbninja.web#10]
not a priority until /trading build out begins.

Question: should we use one URL with common look/feel or split site into two based on URL/content/style?

Question: should xemex.co have common home page for all users to land on?

**Comment by ppantilla** [comment]
generally one look and feel is best for everything within a single brand.   Just augmenting that with  identifiers (i.e. additional logo, diff additional colors) can be sufficient to establish trading vs sports.

but its good to keep the core branding, i.e. logo, primary colors and dominant background color.

**Comment by laisee** [comment]
Agree. 

Are you going to be at a skype-able location today?

**Comment by ppantilla** [comment]
yup am good with skype i think. let me just install on my pc

**Comment by laisee** [comment]
copied this over the right repo: Xemex.web
