### ISSUE TITLE
change icon/logo to use new e-sports.cool title

### ISSUE THREAD

**Issue by laisee** [BBNinja/bbninja.web#11]
use two different colors as with xemex.co, xemex:sport logos

**Comment by ppantilla** [comment]
we could use the same font and the border to signify an implied relationship with xemex.  variations would then be colors.  Reds are probably best for sports.

**Comment by laisee** [comment]
Sounds good, especially on colors

**Comment by ppantilla** [comment]
first draft for logo.  let me know when the second atlantic instance is available so that i can setup.

**Comment by ppantilla** [comment]
instance is up on http://45.58.45.127/. with logo.  for review

**Comment by laisee** [comment]
Got it, thanks

**Comment by laisee** [comment]
Done, will close this one
