### ISSUE TITLE
Update links for BBNinja

### ISSUE THREAD

**Issue by laisee** [BBNinja/bbninja.web#12]
- reduce font size for links
- links at top should be 'sign in', 'register', 'about' + icons for twitter, facebook, instagram etc etc
- links at bottom should be collected into groups a la coinbase.com, bitstamp.com
- links at bottom should also include icons for twitter, facebook, instagram etc etc
- site icon should be positioned on far left side, not indented

**Comment by ppantilla** [comment]
dropping size to 14px

**Comment by ppantilla** [comment]
done

**Comment by laisee** [comment]
Reviewing later today
