### ISSUE TITLE
Site text regarding tokens

### ISSUE THREAD

**Issue by laisee** [BBNinja/bbninja.web#13]
change text to refer to tokens like:

"**GSW** trading in **NFL** league"
"**StephCurrey** plying for **GSW** in **NFL** league"

where **bold text** means a link to the player, team or league will be available

n.b. This is guidance on how to describe the site tokens, provides easy way for people to understand the structure of tokens.

**Comment by ppantilla** [comment]
Changed references. Done.

**Comment by laisee** [comment]
move to "Done" state, pls

**Comment by ppantilla** [comment]
Dont seem to have the permissions to close tickets

**Comment by laisee** [comment]
Let me make you an admin

**Comment by laisee** [comment]
Try to update tasks on waffle board now and/or Github repo
