### ISSUE TITLE
Rename site to e-sports.cool

### ISSUE THREAD

**Issue by laisee** [BBNinja/bbninja.web#9]
Bought URL for e-sports.cool and updated DNS to forward on to bbninja prototype site @ bbninja.herokuapp.com.

**Comment by ppantilla** [comment]
ok, but i think we'll need to somehow work with atlantic so that we can use both http://45.58.40.76/bbninja and the root october install.  i assumed that you kept the atlantic php configuration on 5.6 for that purpose.

**Comment by ppantilla** [comment]
i think i mentioned it somewhere else, but the .profile for http://45.58.40.76 has to be toggled on and off (i.e. renamed to a dff file like .profile ->profile.bak) for http://45.58.40.76/bbninja to become accessible.

**Comment by ppantilla** [comment]
as its the .profile that defines the rewrite rules that lets octobercms run on php 5.6.  currently, it requires php 7.0 to run,.

**Comment by laisee** [comment]
Lets discuss today

**Comment by laisee** [comment]
Browser tab title still shows BBNinja

**Comment by laisee** [comment]
footer still shows "Copyright (c) 2015 BetsnBits.com" and also all the social media sites (fb, twitter, linkedin) show "betsnbits". Please change all betsnbits text to "e-sports.cool"

**Comment by laisee** [comment]
Move "Members to right side and change to "Login". Add a link for people to register if they are not logged in, please this on right side of "login" link.

Community page should have same "Login", "Register" links - don't show the full login or register panels on this page. "Community" can simply be the home page for content, whether user is (auto)logged-in or not.

**Comment by ppantilla** [comment]
took care of the footer items.

**Comment by ppantilla** [comment]
changed this to a single login / register link and page to simplify the whole thing.    Also removing the bitcoin menu item.  Let me know if this works.
